[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_test = "69Qd1B33Uo7PR2JzfC7finFDaccts85pdpoCSMYbNf8K"

[provider]
cluster = "Localnet"
wallet = "./key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node app/*.ts"
